apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: wg-easy
  namespace: wg-easy
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - wireguard
  routes:
    - services:
        - name: wg-easy-udp
          port: 51820