apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: mosquitto