---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-shoemaker-net-staging # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: local-shoemaker-net-staging-tls # change to your secretname
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.shoe-maker.net" # change to your domain
  dnsNames:
  - "local.shoe-maker.net" # change to your domain
  - "*.local.shoe-maker.net" # change to your domain
