---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-plex-smb
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-plex-smb
  storageClassName: smb