---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shoemakernet # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: shoemakernet-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.shoe-maker.net" # change to your domain
  dnsNames:
  - "*.shoe-maker.net" # change to your domain
  - shoe-maker.net # change to your domain
