---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-local-shoemaker-net # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: traefik-local-shoemaker-net-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "traefik.local.shoe-maker.net" # change to your domain
  dnsNames:
  - "traefik.local.shoe-maker.net" # change to your domain
