# https://github.com/dockur/windows
services:
  macos:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      DISK_SIZE: "50G"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
    #  DHCP: "Y" # if enabled you must create a macvlan
      USERNAME: "james"
      PASSWORD: "jimsgarage"
      LANGUAGE: "ENGLISH"
      REGION: "en-GB"
      KEYBOARD: "en-GB"
      GPU: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/dri/renderD128
      - /dev/vfio
      - /dev/dri/card0
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
    networks:
      windows:
        ipv4_address: 172.70.25.2

networks:
  windows:
    ipam:
      config:
        - subnet: 172.70.25.0/29
    name: windows