---
apiVersion: v1
kind: Namespace
metadata:
  name: unifi-controller
---
apiVersion: v1
kind: Secret
metadata:
  name: unifi-env
  namespace: unifi-controller
type: Opaque
stringData:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"
  MONGO_USER: "unifi"
  MONGO_PASS: "5nHgg3G0cH9d"
  MONGO_DBNAME: unifi
